### PR TITLE
Switch to TOML for config format

### PR DESCRIPTION
**Pull request by keirlawson**

### CODE REVIEW

**Comment by andrewinci** [comment]
The [AuthenticationConfig](https://github.com/andrewinci/insulator2/blob/main/src-tauri/src/lib/configuration/types.rs#L30) type is not supported by the toml serde out of the box. It requires a tag `#[serde(tag = "type")]` that will change the way the data is serialised.
Since the serialisation is shared with the frontend, this change will also need to take into account changing the type in the frontend or decoupling the type used in the frontend with the type used in the backend.

**Comment by keirlawson** [comment]
Fixed that issue and revised the TOML format to be a bit nicer, introduced a couple of bugs in the process though so not fit for merging yet

**Comment by keirlawson** [comment]
Starting to think having separate models for config and RPC is actually the way to go...

**Comment by keirlawson** [comment]
Closed in favour of #159

**Pull request closed without merging**
